### ISSUE TITLE
Build release crash

### ISSUE THREAD

**Issue by aboozaid** [servalproject/serval_chat#13]
This is a very strange crash that occurs only in release mode. Here is a snapshot from the exception

```
03-14 03:18:57.208 29649 29665 E AndroidRuntime: Process: com.serval_chat, PID: 29649
03-14 03:18:57.208 29649 29665 E AndroidRuntime: java.lang.IllegalStateException: MDP port was not set
03-14 03:18:57.208 29649 29665 E AndroidRuntime: 	at org.studia.mid.Server.started(Server.java:149)
03-14 03:18:57.208 29649 29665 E AndroidRuntime: 	at org.servalproject.servaldna.ServalDCommand.server(Native Method)
03-14 03:18:57.208 29649 29665 E AndroidRuntime: 	at org.studia.mid.Server.run(Server.java:179)
03-14 03:18:57.208 29649 29665 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

```

It turns out that mdp becomes 0 in release mode (tested on two devices) but 4210 in debug mode

```
                if (mdpPort<=0)
			throw new IllegalStateException("MDP port was not set"); // fired on release mode
		if (httpPort<=0)
			throw new IllegalStateException("HTTP port was not set");

		this.mdpPort = mdpPort;
		this.httpPort = httpPort;

		serval.runOnBackground(new Runnable() {
			@Override
			public void run() {
				serval.onServerStarted();
			}
		});
```

Everything works fine in debug mode.

**Comment by lakeman** [comment]
This is likely to be the native code linker optimising too much. To de-couple some features of serval-dna, we put function tables into code sections so the linker will append them into an array. This includes overlay_mdp_setup_sockets, which is where we bind the mdp service to a udp port.

You could confirm this theory by adding log statements to the [CALL_TRIGGER](https://github.com/servalproject/serval-dna/blob/5ec74ea307386e7501e4fb48a269291f1d62bd74/trigger.h#L37) macro, and comparing the number of methods called by the startup trigger.

**Comment by aboozaid** [comment]
I will try and get back to you. But do you have any illustration why it works well on debugging mode only? I think it should work in release mode except if you add additional props to the native code internally, is this right? I didn't see all the files of the native code yet!

**Comment by aboozaid** [comment]
The same thing happens with serval_chat app when building in release mode

**Comment by assemmohamedali** [comment]
> This is likely to be the native code linker optimising too much. To de-couple some features of serval-dna, we put function tables into code sections so the linker will append them into an array. This includes overlay_mdp_setup_sockets, which is where we bind the mdp service to a udp port.
> 
> You could confirm this theory by adding log statements to the [CALL_TRIGGER](https://github.com/servalproject/serval-dna/blob/5ec74ea307386e7501e4fb48a269291f1d62bd74/trigger.h#L37) macro, and comparing the number of methods called by the startup trigger.

The number of called methods in debugging is 7 but in releasing 6

**Comment by aboozaid** [comment]
> This is likely to be the native code linker optimising too much. To de-couple some features of serval-dna, we put function tables into code sections so the linker will append them into an array. This includes overlay_mdp_setup_sockets, which is where we bind the mdp service to a udp port.
> 
> You could confirm this theory by adding log statements to the [CALL_TRIGGER](https://github.com/servalproject/serval-dna/blob/5ec74ea307386e7501e4fb48a269291f1d62bd74/trigger.h#L37) macro, and comparing the number of methods called by the startup trigger.

I just did this but I couldn't figure out which methods are not get called. @lakeman Could you please try to build serval_chat in release mode and let me know if it works with you?

**Comment by aboozaid** [comment]
UPDATE: conf_schema.h in serval-dna doesn't include this attribute dump_config which you call here
```
if (BuildConfig.BUILD_TYPE.equals("debug")){
				config.set("log.android.level", "DEBUG");
			} else {
				config.set("log.android.level", "WARN");
				/*config.set("log.android.dump_config", "0");
				config.set("log.file.dump_config", "0");*/ causing the issue
			}
```

put a comment fixed the problem. hopefully to fix this bug
